services:
  apk_installer:
    build: .
    volumes:
      - ./:/app/
      - ./ssh:/root/.ssh
    networks:
      - stf_default
    environment:
      - ADB_SERVER_SOCKET=tcp:stf:5037
    restart: unless-stopped
    ports:
      - 8501:8501
networks:
  stf_default:
    external: true
      